name       : qt5-scxml
version    : 5.15.3
release    : 15
source     :
    - git|https://invent.kde.org/qt/qt/qtscxml.git : 7a15000f42c7a3171719727cd056f82a78244ed7
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 SCXML components
description: |
    Qt5 SCXML components
builddeps  :
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
    - devel :
        - /usr/bin
setup      : |
    %qmake CONFIG+=release qtscxml.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
