name       : qt5-scxml
version    : 5.11.1
release    : 2
source     :
    - https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.11/5.11.1/submodules/qtscxml-everywhere-src-5.11.1.tar.xz : f0463f02c0bb81d214b04ec82ff0d22744cdae1966cd8dfb53cd2b31ad233338
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt5 SCXML components
description: |
    Qt5 SCXML components
builddeps  :
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
    - devel :
        - /usr/bin
setup      : |
    %qmake CONFIG+=release qtscxml.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
