name       : qt5-scxml
version    : 5.15.2
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtscxml-everywhere-src-5.15.2.tar.xz : 60b9590b9a41c60cee7b8a8c8410ee4625f0389c1ff8d79883ec5a985638a7dc
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt5 SCXML components
description: |
    Qt5 SCXML components
builddeps  :
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
    - devel :
        - /usr/bin
setup      : |
    %qmake CONFIG+=release qtscxml.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
