name       : qt5-scxml
version    : 5.15.1
release    : 11
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtscxml-everywhere-src-5.15.1.tar.xz : 2289f8c1b51ac368cc0ba8a6a987b44d2c97b43697b00e64582e43afedffcd2b
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt5 SCXML components
description: |
    Qt5 SCXML components
builddeps  :
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
    - devel :
        - /usr/bin
setup      : |
    %qmake CONFIG+=release qtscxml.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
