name       : qt5-scxml
version    : 5.12.1
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtscxml-everywhere-src-5.12.1.tar.xz : 59a2aa1000fe03b0a3eff6fddd21f782e305408fcdd7af1f564a382331cb20b7
license    :
    - GFDL-1.3-only
    - LGPL-3.0-only
component  : programming.library
summary    : Qt5 SCXML components
description: |
    Qt5 SCXML components
builddeps  :
    - pkgconfig(Qt5Qml)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
    - devel :
        - /usr/bin
setup      : |
    %qmake CONFIG+=release qtscxml.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
